export const metadata = { title: 'Privacy Policy — UH Tender Finder' }

export default function Page() {
  return (
    <div className="wrap page max700 legal-page">
      <h1>Privacy Policy</h1>
      <p className="updated">Last updated: <span className="placeholder">[DATE]</span></p>

      <p>This policy explains what information UH Tender Finder ("the Service") collects, why, and how it's protected. It covers your account, your private data within the Service, and the public data the Service surfaces to you.</p>

      <h2>1. Who this covers</h2>
      <p>This policy applies to approved member users of the Service, operated by <span className="placeholder">[LEGAL ENTITY NAME]</span>, <span className="placeholder">[REGISTERED ADDRESS]</span> ("we", "us").</p>

      <h2>2. What we collect</h2>
      <ul>
        <li><strong>Account details</strong> you provide at signup: outlet/company name, contact name, and email address.</li>
        <li><strong>Branch location</strong>, if you choose to provide it: an address and/or Eircode, used to calculate distance to planning leads. This is optional and only used for that purpose.</li>
        <li><strong>Preferences</strong>: the categories, minimum relevance score, and alert settings you configure.</li>
        <li><strong>Pricing data</strong> you create: cost, sell and quantity figures you enter against tender opportunities. This is private to your account and is never shown to other members or made public.</li>
        <li><strong>Documents you upload</strong> (such as a Tax Clearance Certificate or eESPD): stored privately, accessible only to your account, never to other members.</li>
        <li><strong>Contact notes</strong> you add against a planning lead: information you've personally gathered, stored privately to your account.</li>
        <li><strong>Usage data</strong> generated by using the Service, such as saved tenders and login timestamps.</li>
      </ul>

      <h2>3. What we don't collect</h2>
      <p>We don't buy or fabricate contact information for builders, developers, or applicants named in public planning records. Any such information shown to you comes directly from the official public record itself. We don't sell member data to third parties.</p>

      <h2>4. Public data displayed through the Service</h2>
      <p>The Service surfaces publicly available records from eTenders.gov.ie, the national planning application register (Department of Housing, Local Government and Heritage), and the Building Control Management System commencement notice register. This is public information, independent of your account, and its accuracy and completeness is the responsibility of the originating public body, not us. See the Terms of Service for details on how this data is used.</p>

      <h2>5. How your data is stored</h2>
      <p>Account and application data is stored with Supabase (hosted on infrastructure within the EU where configured) using row-level security, meaning your pricing sheets, documents, and private notes are technically restricted to your own account at the database level, not just hidden by the interface. Uploaded documents are held in private object storage and are only ever accessed via short-lived, individually generated links.</p>

      <h2>6. Email alerts</h2>
      <p>If you enable email alerts, your email address is used solely to send you notifications about opportunities matching your preferences. You can disable these at any time from your Preferences page.</p>

      <h2>7. Cookies</h2>
      <p>The Service uses only the essential cookies required to keep you signed in. No advertising or third-party tracking cookies are used.</p>

      <h2>8. Data retention and deletion</h2>
      <p>Your account data is retained for as long as your account is active. To request deletion of your account and associated data, contact <span className="placeholder">[CONTACT EMAIL]</span>.</p>

      <h2>9. Your rights</h2>
      <p>Under GDPR, you have the right to access, correct, or request deletion of your personal data, and to object to or restrict certain processing. To exercise these rights, contact <span className="placeholder">[CONTACT EMAIL]</span>.</p>

      <h2>10. Changes to this policy</h2>
      <p>We may update this policy from time to time. Material changes will be reflected by an updated date at the top of this page.</p>

      <h2>11. Contact</h2>
      <p><span className="placeholder">[CONTACT EMAIL / ADDRESS]</span></p>
    </div>
  )
}
