import { notFound } from 'next/navigation'
import { requireMember } from '@/lib/auth'
import { savePlanningLead,unsavePlanningLead,addPlanningContact,deletePlanningContact } from '@/app/planning/actions'
import { distanceKm } from '@/lib/planning'
function euro(v:number|null){return v==null?'Not estimated':new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v)}
function d(v:string|null){return v?new Intl.DateTimeFormat('en-IE',{dateStyle:'full'}).format(new Date(v)):'Not stated'}
function label(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
export default async function Page({params}:{params:{id:string}}){
 const {supabase,user,profile}=await requireMember();const {data:lead}=await supabase.from('planning_applications').select('*').eq('id',params.id).single();if(!lead)notFound()
 const [{data:saved},{data:contacts}]=await Promise.all([supabase.from('saved_planning_leads').select('planning_id').eq('user_id',user.id).eq('planning_id',lead.id).maybeSingle(),supabase.from('planning_contacts').select('*').eq('user_id',user.id).eq('planning_id',lead.id).order('created_at')])
 const dist=profile.branch_latitude!=null&&profile.branch_longitude!=null&&lead.latitude!=null&&lead.longitude!=null?distanceKm(Number(profile.branch_latitude),Number(profile.branch_longitude),Number(lead.latitude),Number(lead.longitude)):null
 return <div className="wrap page"><div className="detail-head"><div><div className="tender-top"><span className={`badge ${lead.project_stage==='starting_soon'?'soon':'green'}`}>{lead.project_stage.replaceAll('_',' ').toUpperCase()}</span><span className="badge">{label(lead.project_type)}</span>{dist!=null&&<span className="badge">{dist.toFixed(1)} KM FROM BRANCH</span>}{lead.categories?.map((c:string)=><span className="badge" key={c}>{c}</span>)}</div><h1>{lead.development_address||'Planning opportunity'}</h1><p>{lead.planning_authority} · {lead.application_number}</p></div><div className="match-big"><strong>{lead.relevance_score}</strong><span>opportunity /100</span></div></div>
 <div className="detail-grid"><section className="panel"><h2>Project</h2><p className="lead">{lead.development_description||'No development description supplied.'}</p><div className="fact-grid"><div><small>Project type</small><b>{label(lead.project_type)}</b></div><div><small>Estimated merchant opportunity</small><b>{lead.estimated_opportunity_band?`${lead.estimated_opportunity_band} scale`:'Not estimated'}</b>{lead.estimated_opportunity_low!=null&&<div className="muted" style={{fontSize:12,marginTop:2}}>Indicative {euro(lead.estimated_opportunity_low)}–{euro(lead.estimated_opportunity_high)}, not a calculated valuation</div>}</div><div><small>Residential units</small><b>{lead.residential_units??(lead.one_off_house?1:'Not stated')}</b></div><div><small>Floor area</small><b>{lead.floor_area?`${Math.round(lead.floor_area)} m²`:'Not stated'}</b></div><div><small>Received</small><b>{d(lead.received_date)}</b></div><div><small>Granted / decision</small><b>{d(lead.grant_date||lead.decision_date)}</b></div></div><h3>Why it is ranked</h3><p>{lead.score_reason||'Merchant relevance based on project type, scale and stage.'}</p><p className="muted">Material categories and opportunity values are indicative estimates from public project information, not quantities or confirmed orders.</p>
 {lead.commencement_date&&<div className="hot-panel"><h3>🔥 Commencement detected</h3><p><b>Commencement date:</b> {d(lead.commencement_date)}<br/><b>Notice:</b> {lead.commencement_number||'Recorded'}<br/><b>Status:</b> {lead.commencement_status||'Recorded in BCMS data'}</p></div>}
 <h2 className="section-title">People & contacts</h2><div className="people-grid"><div><small>Applicant / owner signal</small><b>{lead.applicant_name||'Not exposed in this record'}</b>{lead.applicant_address&&<p className="muted">{lead.applicant_address}</p>}</div><div><small>Planning agent</small><b>{lead.agent_name||lead.agent_company||'Not exposed in this record'}</b></div><div><small>Main contractor</small><b>{contacts?.find((c:any)=>c.role==='builder')?.company||contacts?.find((c:any)=>c.role==='builder')?.name||'Not identified yet'}</b></div></div>
 {!lead.applicant_name&&!lead.agent_name&&!lead.agent_company&&!(contacts||[]).length&&<div className="notice-box"><b>No contact details are published for this application.</b> The official record doesn't include builder or developer contact information, and this tool never invents one. If you know who's involved, add it below, it's kept private to your account only.</div>}
 {(contacts||[]).length>0&&<div className="contact-list">{contacts!.map((c:any)=><div className="contact-row" key={c.id}><div><b>{c.company||c.name}</b> <span className="badge">{label(c.role)}</span>{c.company&&<div>{c.name}</div>}<small>{[c.phone,c.email].filter(Boolean).join(' · ')}</small>{c.notes&&<p>{c.notes}</p>}</div><form action={deletePlanningContact.bind(null,lead.id,c.id)}><button className="btn btn-sm btn-ghost">Remove</button></form></div>)}</div>}
 <details className="contact-add" open={!lead.applicant_name&&!lead.agent_name&&!lead.agent_company&&!(contacts||[]).length}><summary>I know who is involved in this job</summary><form action={addPlanningContact.bind(null,lead.id)} className="contact-form"><div className="field-row"><div className="field"><label>Role</label><select name="role"><option value="builder">Main contractor / builder</option><option value="developer">Developer</option><option value="architect">Architect / agent</option><option value="engineer">Engineer</option><option value="plumber">Plumbing contractor</option><option value="heating_contractor">Heating contractor</option><option value="owner">Owner</option><option value="other">Other</option></select></div><div className="field"><label>Contact name *</label><input name="name" required/></div></div><div className="field-row"><div className="field"><label>Company</label><input name="company"/></div><div className="field"><label>Relationship</label><select name="source"><option value="member">Local knowledge</option><option value="existing_customer">Existing customer</option><option value="public_source">Public source</option></select></div></div><div className="field-row"><div className="field"><label>Phone</label><input name="phone"/></div><div className="field"><label>Email</label><input name="email" type="email"/></div></div><div className="field"><label>Notes</label><textarea name="notes" rows={3}/></div><button className="btn btn-primary">Add contact</button><p className="muted">This contact note is private to your member account.</p></form></details>
 </section><aside className="side-stack"><section className="panel"><h3>Sales signal</h3><p>{lead.project_stage==='starting_soon'?<><b>High urgency.</b> A commencement has been matched to this planning permission.</>:lead.project_stage==='granted'?<><b>Permission granted.</b> Watch for a commencement or identify the builder before procurement starts.</>:<>Early-stage opportunity. Monitor the planning decision.</>}</p></section><section className="panel action-panel">{lead.source_url&&<a className="btn btn-primary btn-full" href={lead.source_url} target="_blank" rel="noreferrer">Open official planning record ↗</a>}{lead.commencement_source_url&&<a className="btn btn-secondary btn-full" href={lead.commencement_source_url} target="_blank" rel="noreferrer">Open BCMS register ↗</a>}{saved?<form action={unsavePlanningLead.bind(null,lead.id)}><button className="btn btn-ghost btn-full">Remove from saved</button></form>:<form action={savePlanningLead.bind(null,lead.id)}><button className="btn btn-ghost btn-full">Save opportunity</button></form>}</section><section className="panel"><h3>Data boundary</h3><p className="muted">Planning data identifies the project and public application details. BCMS open data can identify a commencement, but it does not publish builder names in the national open dataset. Never assume a contractor unless a reliable source or member confirms it.</p></section></aside></div></div>
}
